start:
  deps: [install, bf]

bar:
  deps: [build, bf]
  cmds:
    - ./VueJsPlayground

build:
  cmds:
    - go build

br:
  cmds:
    - go build
    - ./VueJsPlayground

bf:
  cmds:
    - npm run build
    - mkdir ./dist/static/media/

install:
  cmds:
    - npm install
